In [1]:
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, recall_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv("novagen_dataset.csv")

In [3]:
df.describe()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,Target,Smoking,Alcohol,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies
count,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000,9549.000000
mean,33.806786,25.660697,130.382658,199.091528,100.225678,73.613782,6.951409,1.892345,3.580899,4.382134,0.521416,0.990470,0.995183,1.005864,0.998429,1.003351,1.004713,0.989318
std,24.566473,1.942369,27.878476,1.969234,2.157999,1.681538,2.352152,1.378714,1.622874,2.078593,0.499567,0.815521,0.816653,0.815877,0.821844,0.808800,0.813506,0.815699
min,0.000000,19.000000,22.000000,192.000000,93.000000,67.000000,-0.000000,-0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,14.000000,24.000000,113.000000,198.000000,99.000000,73.000000,5.000000,1.000000,2.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,29.000000,26.000000,134.000000,199.000000,100.000000,74.000000,7.000000,2.000000,4.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
75%,50.000000,27.000000,150.000000,200.000000,102.000000,75.000000,9.000000,3.000000,5.000000,6.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000
max,100.000000,32.000000,225.000000,207.000000,107.000000,80.000000,14.000000,8.000000,10.000000,12.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000

In [4]:
X= df.drop("Target", axis=1)
y= df["Target"]

X_train, X_test, y_train, y_test= train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [5]:
scaler= StandardScaler()
X_train_scaled= scaler.fit_transform(X_train)
X_test_scaled= scaler.transform(X_test)

# Model 1 - Logistic Regression

In [6]:
lr=LogisticRegression(
    penalty="l2",
    max_iter= 1000,
    random_state=42
)
lr.fit(X_train_scaled, y_train)
y_pred_lr= lr.predict(X_test_scaled)

print("Acccuracy is", accuracy_score(y_test, y_pred_lr))
print("Recall is", recall_score(y_test, y_pred_lr))
print("CR-LR", classification_report(y_test, y_pred_lr))

Acccuracy is 0.8225130890052356
Recall is 0.8376237623762376
CR-LR               precision    recall  f1-score   support

           0       0.82      0.81      0.81       900
           1       0.83      0.84      0.83      1010

    accuracy                           0.82      1910
   macro avg       0.82      0.82      0.82      1910
weighted avg       0.82      0.82      0.82      1910

# Model 2 - KNN

In [7]:
knn= KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)
y_pred_knn=knn.predict(X_test_scaled)

print("Acccuracy is", accuracy_score(y_test, y_pred_knn))
print("Recall is", recall_score(y_test, y_pred_knn))
print("CR-KNN", classification_report(y_test, y_pred_knn))

Acccuracy is 0.8717277486910995
Recall is 0.8693069306930693
CR-KNN               precision    recall  f1-score   support

           0       0.86      0.87      0.87       900
           1       0.89      0.87      0.88      1010

    accuracy                           0.87      1910
   macro avg       0.87      0.87      0.87      1910
weighted avg       0.87      0.87      0.87      1910

# Model 3 - Decision Tree

In [8]:
dt= DecisionTreeClassifier(max_depth=5)
dt.fit(X_train_scaled, y_train)
y_pred_dt= dt.predict(X_test_scaled)

print("Acccuracy is", accuracy_score(y_test, y_pred_dt))
print("Recall is", recall_score(y_test, y_pred_dt))
print("CR-DT", classification_report(y_test, y_pred_dt))

Acccuracy is 0.856020942408377
Recall is 0.9217821782178218
CR-DT               precision    recall  f1-score   support

           0       0.90      0.78      0.84       900
           1       0.83      0.92      0.87      1010

    accuracy                           0.86      1910
   macro avg       0.86      0.85      0.85      1910
weighted avg       0.86      0.86      0.85      1910

# Random Forest Model

In [9]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=9, 
    random_state=42,
)

rf.fit(X_train_scaled, y_train)
y_pred_rf= rf.predict(X_test_scaled)
print("Recall:", recall_score(y_test, y_pred_rf))
print("testing accuracy", accuracy_score(y_test, y_pred_rf))
print("CR-RF", classification_report(y_test, y_pred_rf))

Recall: 0.9475247524752475
testing accuracy 0.9287958115183246
CR-RF               precision    recall  f1-score   support

           0       0.94      0.91      0.92       900
           1       0.92      0.95      0.93      1010

    accuracy                           0.93      1910
   macro avg       0.93      0.93      0.93      1910
weighted avg       0.93      0.93      0.93      1910

# Gradient Boosting Homogeneous Ensemble Model

In [12]:
gb= GradientBoostingClassifier(
    n_estimators=200,
    learning_rate=0.1, 
    max_depth=5, 
    random_state=42
)
gb.fit(X_train_scaled, y_train)
y_pred_gb= gb.predict(X_test_scaled)

print("Recall:", recall_score(y_test, y_pred_gb))
print("testing accuracy", accuracy_score(y_test, y_pred_gb))
print("CR-GB", classification_report(y_test, y_pred_gb))

Recall: 0.9485148514851485
testing accuracy 0.9465968586387434
CR-GB               precision    recall  f1-score   support

           0       0.94      0.94      0.94       900
           1       0.95      0.95      0.95      1010

    accuracy                           0.95      1910
   macro avg       0.95      0.95      0.95      1910
weighted avg       0.95      0.95      0.95      1910

# Voting Heterogeneous Ensemble Model

In [13]:
vc= VotingClassifier(
    estimators=[("Logistic Regression", lr),
                ("KNN", knn),
                ("Decision Tree", dt),
                ("Random Forest", rf)],
    voting="hard"
)
vc.fit(X_train_scaled, y_train)
y_pred_vc= vc.predict(X_test_scaled)

print("Recall:", recall_score(y_test, y_pred_vc))
print("testing accuracy", accuracy_score(y_test, y_pred_vc))
print("CR-VC", classification_report(y_test, y_pred_vc))

Recall: 0.902970297029703
testing accuracy 0.9068062827225131
CR-VC               precision    recall  f1-score   support

           0       0.89      0.91      0.90       900
           1       0.92      0.90      0.91      1010

    accuracy                           0.91      1910
   macro avg       0.91      0.91      0.91      1910
weighted avg       0.91      0.91      0.91      1910

In [14]:
df.columns

Index(['Age', 'BMI', 'Blood_Pressure', 'Cholesterol', 'Glucose_Level',
       'Heart_Rate', 'Sleep_Hours', 'Exercise_Hours', 'Water_Intake',
       'Stress_Level', 'Target', 'Smoking', 'Alcohol', 'Diet', 'MentalHealth',
       'PhysicalActivity', 'MedicalHistory', 'Allergies', 'Diet_Type__Vegan',
       'Diet_Type__Vegetarian', 'Blood_Group_AB', 'Blood_Group_B',
       'Blood_Group_O'],
      dtype='object')

In [15]:
import joblib

# Save the model to a file
joblib.dump(gb, 'NovaGen.pkl')

# Optional: Save the scaler as well (you'll need it for preprocessing new data)
joblib.dump(scaler, 'scaler.pkl')

print("Model saved successfully using joblib!")

Model saved successfully using joblib!

In [18]:
X_train

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
180,13.0,25.0,97.0,197.0,99.0,73.0,7.0,2.0,5.0,3.0,...,1,2,1,0,1,False,False,False,False,False
1115,77.0,26.0,130.0,203.0,97.0,72.0,8.0,2.0,3.0,1.0,...,0,2,1,1,1,False,True,True,False,False
4398,3.0,27.0,149.0,198.0,103.0,73.0,8.0,2.0,4.0,5.0,...,2,0,1,2,1,True,False,True,False,False
8265,1.0,23.0,147.0,198.0,104.0,73.0,3.0,4.0,2.0,9.0,...,2,0,1,1,1,True,False,True,False,False
9469,9.0,24.0,147.0,199.0,98.0,72.0,7.0,0.0,4.0,2.0,...,0,0,2,2,2,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5734,14.0,24.0,132.0,198.0,99.0,73.0,7.0,1.0,3.0,4.0,...,1,2,1,1,2,True,False,False,False,False
5191,13.0,25.0,126.0,197.0,101.0,75.0,10.0,1.0,4.0,4.0,...,0,0,2,2,2,False,False,False,False,True
5390,14.0,25.0,118.0,199.0,102.0,73.0,4.0,-0.0,2.0,7.0,...,0,0,2,1,2,False,False,False,False,True
860,19.0,27.0,129.0,197.0,100.0,73.0,8.0,1.0,3.0,5.0,...,0,0,0,2,0,False,False,False,False,True
7270,6.0,25.0,154.0,198.0,100.0,75.0,4.0,2.0,4.0,6.0,...,2,0,1,0,1,False,True,True,False,False

In [19]:
df

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9544,5.0,22.0,109.0,203.0,98.0,75.0,8.0,1.0,6.0,0.0,...,0,2,2,1,0,True,False,True,False,False
9545,94.0,26.0,144.0,203.0,96.0,72.0,8.0,4.0,2.0,1.0,...,1,0,1,0,2,False,True,False,True,False
9546,10.0,23.0,185.0,198.0,103.0,72.0,4.0,5.0,5.0,6.0,...,1,0,2,0,1,True,False,True,False,False
9547,50.0,29.0,166.0,200.0,100.0,74.0,8.0,2.0,3.0,4.0,...,2,0,0,1,1,True,False,True,False,False
9548,69.0,29.0,178.0,203.0,100.0,75.0,10.0,-0.0,6.0,2.0,...,1,2,1,2,0,False,False,True,False,False